# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e013e949259ab28ea0abaf42df977b73cb3826c6b66bafa547075c8f69adba1a36b5ae7d0a1eb519489be1ef0054e1183e3926d068c5e51a422bbf648c45362

test:
  secret_key_base: 58d9c0bf6e7a87ad82036aa310740c1932509e10c74a8b8ca81c0b172b6ea81fb8a50a14f8266e80d9493eae5c93cb2d0b53c7ace4435e5feadd2694fbc8349f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
